### ISSUE TITLE
Non Payment terminal recognised as Payment Terminal by default

### ISSUE THREAD

**Issue by dansanti** [TransbankDevelopers/transbank-pos-sdk-web-agent#45]
Hello, 

If windows PC has another device like a USB scale connected, this cause that by default on start, that device's COM was used as terminal.

Could you hard code allowed devices models ? or a way to "remember" selected COM after closed agent?

**Comment by gasspper** [comment]
Hi @dansanti, that happens because the communication is through COM ports, and in this case, you should manage them manually, we cannot create a list of devices because we would be limiting possible integrations of people, and you can configure a way to remember the COM port, but it cannot be from the SDK side either, precisely in case someone has other COM connections on their system.

**Comment by dansanti** [comment]
hello, but there are not a way to "remember" COM selected ?

**Comment by mastudillot** [comment]
@dansanti That functionality can be implemented on your side, you can persist the COM port in the way you deem best.
